
   <!-- Header Space -->
    <div class="header-space"></div>
    <!-- Header Section End -->
	<!-- Breadcrumbs & Page Title Start -->
	<div class="breadcrumbs-title white-bg pt-90 pb-80">
		<div class="container">
			<div class="row">
				<div class="col-xs-12">
					<div class="breadcrumbs-menu">
						<h2>Notre équipe</h2>
						<ul class="clearfix">
							<li><a href="index.php">Retour</a><span>|</span> </li>
							<li>Notre équipe</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- Breadcrumbs & Page Title End -->
	<!-- Our Team Section Start -->
	<div class="team-area pt-80 white-bg">
		<div class="container">
			<div class="row">
				<div class="col-xs-12 text-center">
					<div class="section-title pb-80">
						<h2 class="mb-15">Découvrez le <span class="theme-color">Collectif</span></h2>
						<p>Artistes et créatifs passionnés.</p>
					</div>
				</div>
			</div>
			<div class="row text-center">
				<div class="col-xs-12 col-sm-6 col-md-3 mobi-mb-30 tab-mb-50">
					<div class="team-member white-bg">
						<img src="assets/img/equipe-partenaires/marie.jpg" alt="Marie Chambaud, chef de projet digital, web designer, web developpeur" />
						<h3 class="mb-5">Marie</h3>
						<h6 class="mb-15">Web Designer | Web Dev</h6>
						<p>Diplomée d'un master en com' digitale, je suis votre interlocuteur privilégiée.</p>
						<div class="social-icon style1 text-center mt-20">
							<ul class="clearfix">
								<!--<li><a href="https://www.facebook.com/" target="_blank"><i class="zmdi zmdi-facebook"></i></a></li>-->
								<li><a href="https://www.instagram.com/mdesign_fr/" target="_blank"><i class="zmdi zmdi-instagram"></i></a></li>
								<li><a href="https://www.linkedin.com/in/mariechambaud/" target="_blank"><i class="zmdi zmdi-linkedin"></i></a></li>
								<li><a href="https://twitter.com/mdesign_fr" target="_blank"><i class="zmdi zmdi-twitter"></i></a></li>
							</ul>
						</div>
						<!-- Change your social media link -->
					</div>
				</div>
				<!-- Team Mamber End -->
				<div class="col-xs-12 col-sm-6 col-md-3 mobi-mb-30 tab-mb-50">
					<div class="team-member white-bg">
						<img src="assets/img/equipe-partenaires/laurine.jpg" alt="Laurine Bailly, graphiste" />
						<h3 class="mb-5">Laurine</h3>
						<h6 class="mb-15">Graphiste | Designer</h6>
						<p>Diplomée d'une licence en Art et Design, je créée votre identité visuelle sur mesure.</p>
						<div class="social-icon style1 text-center mt-20">
							<ul class="clearfix">
								<!-- <li><a href="https://www.facebook.com/" target="_blank"><i class="zmdi zmdi-facebook"></i></a></li>
								<li><a href="https://twitter.com/" target="_blank"><i class="zmdi zmdi-twitter"></i></a></li> -->
								<li><a href="https://www.instagram.com/turquoisemercury/" target="_blank"><i class="zmdi zmdi-instagram"></i></a></li>
								<li><a href="https://www.linkedin.com/in/laurinebailly/" target="_blank"><i class="zmdi zmdi-linkedin"></i></a></li>
							</ul>
						</div>
						<!-- Change your social media link -->
					</div>
				</div>
				<!-- Team Mamber End -->
				<div class="col-xs-12 col-sm-6 col-md-3 mobi-mb-30 tab-mb-50">
					<div class="team-member white-bg">
						<img src="assets/img/equipe-partenaires/alisea.jpg" alt="Alisea, photographe portrait" />
						<h3 class="mb-5">Alisea</h3>
						<h6 class="mb-15">Photographe</h6>
						<p>Photographe portrait, mode, packshot. Des visuels de qualité pour votre site.</p>
						<div class="social-icon style1 text-center mt-20">
							<ul class="clearfix">
								<!-- <li><a href="https://www.facebook.com/" target="_blank"><i class="zmdi zmdi-facebook"></i></a></li>
								<li><a href="https://twitter.com/" target="_blank"><i class="zmdi zmdi-twitter"></i></a></li> -->
								<li><a href="https://www.instagram.com/ambrosinoalisea/" target="_blank"><i class="zmdi zmdi-instagram"></i></a></li>
								<!-- <li><a href="https://www.pinterest.com/" target="_blank"><i class="zmdi zmdi-pinterest"></i></a></li> -->
							</ul>
						</div>
						<!-- Change your social media link -->
					</div>
				</div>
				<!-- Team Mamber End -->
				<div class="col-xs-12 col-sm-6 col-md-3 mobi-mb-30 tab-mb-50">
					<div class="team-member white-bg">
						<img src="assets/img/equipe-partenaires/dev.jpg" alt="Sylvain, développeur expert" />
						<h3 class="mb-5">Sylvain</h3>
						<h6 class="mb-15">Développeur expert</h6>
						<p>Les lignes de code n'ont plus de secrets pour lui. Vos fonctionnalités sur mesure.</p>
						<div class="social-icon style1 text-center mt-20">
							<ul class="clearfix">
								<!-- <li><a href="https://www.facebook.com/" target="_blank"><i class="zmdi zmdi-facebook"></i></a></li>
								<li><a href="https://twitter.com/" target="_blank"><i class="zmdi zmdi-twitter"></i></a></li>
								<li><a href="https://instagram.com/" target="_blank"><i class="zmdi zmdi-instagram"></i></a></li> -->
								<!-- <li><a href="https://www.linkedin.com/company/37-5/" target="_blank"><i class="zmdi zmdi-linkedin"></i></a></li> -->
							</ul>
						</div>
						<!-- Change your social media link -->
					</div>
				</div>
				<!-- Team Mamber End -->
			</div>
			<!-- Row End -->

			<!-- Breadcrumbs & Page Title Start -->
	<div class="breadcrumbs-title white-bg pt-90 pb-50">
		<div class="container">
			<div class="row">
				<div class="col-xs-12 text-center">
					<div class="section-title pb-50">
						<h2 class="mb-15">Nos <span class="theme-color">Partenaires</span></h2>
						<p>Agences et prestataires de qualité.</p>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- Breadcrumbs & Page Title End -->

			<div class="row text-center mb-30">
				<div class="col-xs-12 col-sm-6 col-md-3 mobi-mb-30 tab-mb-50">
					<div class="team-member white-bg">
						<img src="assets/img/equipe-partenaires/37.5.jpg" alt="Agence de conseil stratégique 37.5" />
						<h3 class="mb-5">37.5</h3>
						<h6 class="mb-15">Agence de conseil</h6>
						<p>Stratégie d'entreprise et transformation</p>
						<div class="social-icon style1 text-center mt-20">
							<ul class="clearfix">
								<li><a href="https://www.facebook.com/" target="_blank"><i class="zmdi zmdi-facebook"></i></a></li>
								<li><a href="https://twitter.com/" target="_blank"><i class="zmdi zmdi-twitter"></i></a></li>
								<li><a href="https://instagram.com/" target="_blank"><i class="zmdi zmdi-instagram"></i></a></li>
								<li><a href="https://fr.linkedin.com/company/37-5" target="_blank"><i class="zmdi zmdi-linkedin"></i></a></li>
							</ul>
						</div>
						<!-- Change your social media link -->
					</div>
				</div>
				<!-- Team Mamber End -->
				<div class="col-xs-12 col-sm-6 col-md-3 mobi-mb-30 tab-mb-50">
					<div class="team-member white-bg">
						<img src="assets/img/equipe-partenaires/alhena.jpg" alt="Agence Alhena Conseil" />
						<h3 class="mb-5">Alhena Conseil</h3>
						<h6 class="mb-15">Conseil en communication</h6>
						<p>Complémentarité et synergie "on point" !</p>
						<div class="social-icon style1 text-center mt-20">
							<ul class="clearfix">
								<!-- <li><a href="https://www.facebook.com/" target="_blank"><i class="zmdi zmdi-facebook"></i></a></li> -->
								<li><a href="https://twitter.com/alhena_conseil" target="_blank"><i class="zmdi zmdi-twitter"></i></a></li>
								<li><a href="https://www.instagram.com/alhena_agency/" target="_blank"><i class="zmdi zmdi-instagram"></i></a></li>
								<li><a href="https://www.linkedin.com/company/alhena/" target="_blank"><i class="zmdi zmdi-linkedin"></i></a></li>
							</ul>
						</div>
						<!-- Change your social media link -->
					</div>
				</div>
				<!-- Team Mamber End -->
				<div class="col-xs-12 col-sm-6 col-md-3 mobi-mb-30 tab-mb-50">
					<div class="team-member white-bg">
						<img src="assets/img/equipe-partenaires/allo.jpg" alt="Agence Allô La Com" />
						<h3 class="mb-5">Allo La Com</h3>
						<h6 class="mb-15">Agence de communication</h6>
						<p>Complémentarité et synergie "on point" !</p>
						<div class="social-icon style1 text-center mt-20">
							<ul class="clearfix">
								<!-- <li><a href="https://www.facebook.com/" target="_blank"><i class="zmdi zmdi-facebook"></i></a></li> -->
								<li><a href="https://twitter.com/allolacom" target="_blank"><i class="zmdi zmdi-twitter"></i></a></li>
								<li><a href="https://www.instagram.com/allolacom/" target="_blank"><i class="zmdi zmdi-instagram"></i></a></li>
								<li><a href="https://www.linkedin.com/company/all%C3%B4-la-com/" target="_blank"><i class="zmdi zmdi-linkedin"></i></a></li>
							</ul>
						</div>
						<!-- Change your social media link -->
					</div>
				</div>
				<!-- Team Mamber End -->
				<div class="col-xs-12 col-sm-6 col-md-3">
					<div class="team-member white-bg">
						<img src="assets/img/equipe-partenaires/la_quincaillerie.jpg" alt="OVH" />
						<h3 class="mb-5">La Quincaillerie</h3>
						<h6 class="mb-15">Agence de développement</h6>
						<p>Des jeunes sympas, créatifs, talentueux</p>
						<div class="social-icon style1 text-center mt-20">
							<ul class="clearfix">
								<li><a href="https://www.facebook.com/agencelaquincaillerie/" target="_blank"><i class="zmdi zmdi-facebook"></i></a></li>
								<!--<li><a href="https://twitter.com/" target="_blank"><i class="zmdi zmdi-twitter"></i></a></li>
								<li><a href="https://instagram.com/" target="_blank"><i class="zmdi zmdi-instagram"></i></a></li>
								<li><a href="https://www.pinterest.com/" target="_blank"><i class="zmdi zmdi-pinterest"></i></a></li> -->
							</ul>
						</div>
						<!-- Change your social media link -->
					</div>
				</div>
				<!-- Team Mamber End -->
			</div>
			<!-- Row End -->

			<div class="row text-center mb-30">
				<div class="col-xs-12 col-sm-6 col-md-3 mobi-mb-30 tab-mb-50">
					<div class="team-member white-bg">
						<img src="assets/img/equipe-partenaires/cin.jpg" alt="Carrefour de l'innovation et du numérique" />
						<h3 class="mb-5">C-IN</h3>
						<h6 class="mb-15">Carrefour de l'innovation</h6>
						<p>Catalyseur de projets technologiques</p>
						<div class="social-icon style1 text-center mt-20">
							<ul class="clearfix">
								<li><a href="https://www.facebook.com/Carrefourinnovationnumerique/" target="_blank"><i class="zmdi zmdi-facebook"></i></a></li>
								<!-- <li><a href="https://twitter.com/" target="_blank"><i class="zmdi zmdi-twitter"></i></a></li>
								<li><a href="https://instagram.com/" target="_blank"><i class="zmdi zmdi-instagram"></i></a></li>
								<li><a href="https://www.pinterest.com/" target="_blank"><i class="zmdi zmdi-pinterest"></i></a></li> -->
							</ul>
						</div>
						<!-- Change your social media link -->
					</div>
				</div>
				<!-- Team Mamber End -->
				<div class="col-xs-12 col-sm-6 col-md-3 mobi-mb-30 tab-mb-50">
					<div class="team-member white-bg">
						<img src="assets/img/equipe-partenaires/cce13.jpg" alt="Club des créateurs du 13" />
						<h3 class="mb-5">CCE 13</h3>
						<h6 class="mb-15">Club des créateurs du 13</h6>
						<p>Accompagnement des porteurs de projets</p>
						<div class="social-icon style1 text-center mt-20">
							<ul class="clearfix">
								<li><a href="https://www.facebook.com/clubcreateurs13/" target="_blank"><i class="zmdi zmdi-facebook"></i></a></li>
							<!-- 	<li><a href="https://twitter.com/alhena_conseil" target="_blank"><i class="zmdi zmdi-twitter"></i></a></li>
								<li><a href="https://www.instagram.com/alhena_agency/" target="_blank"><i class="zmdi zmdi-instagram"></i></a></li> -->
								<li><a href="https://www.linkedin.com/in/cce13/" target="_blank"><i class="zmdi zmdi-linkedin"></i></a></li>
							</ul>
						</div>
						<!-- Change your social media link -->
					</div>
				</div>
				<!-- Team Mamber End -->
				<div class="col-xs-12 col-sm-6 col-md-3 mobi-mb-30">
					<div class="team-member white-bg">
						<img src="assets/img/equipe-partenaires/moo.jpg" alt="MOO, imprimeur partenaire de M-DESIGN" />
						<h3 class="mb-5">MOO</h3>
						<h6 class="mb-15">Imprimeur</h6>
						<p>Cartes de visite et supports marketing de qualité</p>
						<div class="social-icon style1 text-center mt-20">
							<ul class="clearfix">
								<!-- <li><a href="https://www.facebook.com/" target="_blank"><i class="zmdi zmdi-facebook"></i></a></li> -->
								<li><a href="https://twitter.com/MOO" target="_blank"><i class="zmdi zmdi-twitter"></i></a></li>
								<li><a href="https://www.instagram.com/moo/" target="_blank"><i class="zmdi zmdi-instagram"></i></a></li>
								<!-- <li><a href="https://www.pinterest.com/" target="_blank"><i class="zmdi zmdi-pinterest"></i></a></li> -->
							</ul>
						</div>
						<!-- Change your social media link -->
					</div>
				</div>
				<!-- Team Mamber End -->
				<div class="col-xs-12 col-sm-6 col-md-3">
					<div class="team-member white-bg">
						<img src="assets/img/equipe-partenaires/ovh.jpg" alt="OVH, hebergement web partenaire de M-Design" />
						<h3 class="mb-5">OVH</h3>
						<h6 class="mb-15">Hebergement web</h6>
						<p>Un hebergement sûr et une interface intuitive</p>
						<div class="social-icon style1 text-center mt-20">
							<ul class="clearfix">
								<!-- <li><a href="https://www.facebook.com/" target="_blank"><i class="zmdi zmdi-facebook"></i></a></li>
								<li><a href="https://twitter.com/" target="_blank"><i class="zmdi zmdi-twitter"></i></a></li>
								<li><a href="https://instagram.com/" target="_blank"><i class="zmdi zmdi-instagram"></i></a></li>
								<li><a href="https://www.pinterest.com/" target="_blank"><i class="zmdi zmdi-pinterest"></i></a></li> -->
							</ul>
						</div>
						<!-- Change your social media link -->
					</div>
				</div>
				<!-- Team Mamber End -->
			</div>
			<!-- Row End -->
		</div>
	</div>
	<!-- Our Team Section End -->


    <!-- Testimonial Section Start -->
    <div class="testimonial-area white-bg section-pt pb-80">
        <div class="container">
            <div class="row text-center">
                
            </div>
        </div>
    </div>
    <!-- Testimonial Section End -->


    <!-- Call To Action Section Start -->
	<div class="cta-one theme-bg ptb-75">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <div class="cta-content clearfix">
                        <div class="pull-left">
                            <h1 style="color: #ffffff;">Prêt à démarrer votre projet digital ?</h1>
                        </div>
                        <div class="pull-right mr-100">
                            <a href="index.php#contact_form" class="btn">OUI !</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Call To Action Section End -->

 