<body>

    <!-- Loading Bar Start -->
    <!-- <div id="loading-wrap">
        <div class="loading-effect"></div>
    </div> -->
    <!-- Loading Bar End -->
    

    <!-- Header Section Start -->
    <header>

            <nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light">
                <div class=" container container-fluid">

                    <a class="navbar-brand" href="/"><img src='/assets/img/logo-baudstudio-design-aix-en-provence.png' alt="Logo de Baudstudio"></a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                            <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="/">Accueil</a>
                            </li>

                            <li class="nav-item">
                            <a class="nav-link" href="/vue/front/pages/a-propos.php">A propos</a>
                            </li>

                            <!-- <li class="nav-item">
                            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Services</a>
                            </li> -->

                            <!-- <li class="nav-item">
                            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Formations</a>
                            </li> -->

                            <li class="nav-item">
                            <a class="nav-link" href="/vue/front/pages/portfolio.php">Portfolio</a>
                            </li>

                            <li class="nav-item">
                            <a class="nav-link" href="/#contact_form">Contact</a>
                            </li>

                        </ul>
                    </div>
                </div>
            </nav>
                                    

    </header>
    <!-- Header Space -->
    <!-- Header Section End -->